### ISSUE TITLE
No such file or directory - /var/lib/nubic/db.pass

### ISSUE THREAD

**Issue by phlegx** [northwestern-fsm/bcdatabase#5] opened 2011-02-17 22:15 UTC
Hi, me again. The following error occurs:

<code>
bcdatabase epass
Password (^C to end): 
/usr/lib/ruby/gems/1.8/gems/bcdatabase-1.0.4/lib/bcdatabase.rb:48:in `initialize': No such file or directory - /var/lib/nubic/db.pass (Errno::ENOENT)
    from /usr/lib/ruby/gems/1.8/gems/bcdatabase-1.0.4/lib/bcdatabase.rb
:48:in`open'
    from /usr/lib/ruby/gems/1.8/gems/bcdatabase-1.0.4/lib/bcdatabase.rb:48:in `pass'
    from /usr/lib/ruby/gems/1.8/gems/bcdatabase-1.0.4/lib/bcdatabase.rb:40:in`encipher'
    from /usr/lib/ruby/gems/1.8/gems/bcdatabase-1.0.4/lib/bcdatabase.rb:22:in `encrypt'
    from /usr/lib/ruby/gems/1.8/gems/bcdatabase-1.0.4/lib/bcdatabase/commands.rb:64:in`interactive'
    from /usr/lib/ruby/gems/1.8/gems/bcdatabase-1.0.4/lib/bcdatabase/commands.rb:60:in `loop'
    from /usr/lib/ruby/gems/1.8/gems/bcdatabase-1.0.4/lib/bcdatabase/commands.rb:60:in`interactive'
    from /usr/lib/ruby/gems/1.8/gems/bcdatabase-1.0.4/lib/bcdatabase/commands.rb:46:in `main'
    from /usr/lib/ruby/gems/1.8/gems/bcdatabase-1.0.4/bin/bcdatabase:26
    from /usr/bin/bcdatabase:19:in`load'
    from /usr/bin/bcdatabase:19
</code>

and:

<code>
bcdatabase gen-key
/usr/lib/ruby/gems/1.8/gems/bcdatabase-1.0.4/lib/bcdatabase/commands.rb:191:in `initialize': No such file or directory - /var/lib/nubic/db.pass (Errno::ENOENT)
    from /usr/lib/ruby/gems/1.8/gems/bcdatabase-1.0.4/lib/bcdatabase/commands.rb:191:in`open'
    from /usr/lib/ruby/gems/1.8/gems/bcdatabase-1.0.4/lib/bcdatabase/commands.rb:191:in `main'
    from /usr/lib/ruby/gems/1.8/gems/bcdatabase-1.0.4/bin/bcdatabase:26
    from /usr/bin/bcdatabase:19:in`load'
    from /usr/bin/bcdatabase:19
</code>

Also /etc/nubic/.. does not exist
Seems that those paths have not been created on "sudo gem install bcdatabse". do they need to be crated manually?

best
phlegx

**Comment by rsutphin** [comment] 2011-02-17 23:01
The first part of this is a duplicate of issue #1.

No paths are created when you install the gem.  You need to create them yourself.  This should probably be in the README, I agree.

Also, since the default key directory is under `/var`, you will either need to run `gen-key` with sudo or change the key directory by setting `BCDATABASE_PASS`.

**Comment by phlegx** [comment] 2011-02-17 23:21
Ok, thx for the explanation!

**Closed as completed** 2011-02-18 07:01 UTC
